baseURL = "/"
title = "Istio By Example"
theme = "hugo-notepadium"
copyright = ""

publishDir = "docs"

languageCode = "ja"
hasCJKLanguage = true # use Japanese in summary and word count

enableRobotsTXT = false

#googleAnalytics = "UA-41949399-6"

[markup.highlight]
codeFences = true
noClasses = false

[markup.goldmark.renderer]
unsafe = true  # enable raw HTML in Markdown

[params]
logo = "/images/istio-logo.png"  # if you have a logo png
slogan = ""
license = ""  # CC License
images = ["/images/istio-logo.png"]

[params.syntax]
use = "chroma"  # builtin: "prismjs", "hljs". "none" means Chroma
theme = "borland"
darkTheme = "xcode-dark"  # apply this theme in dark mode
webFonts = true  # builtin: 'Source Code Pro'

[params.nav]
showCategories = false       # /categories/
showTags = false             # /tags/
